services:
  - type: web
    name: hyperliquid-funding-tracker
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 